name: Hello World
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: "GitHubActions"
          buildspec-override: |
            version: 0.2
            phases:
              pre_build:
                commands:
                  - echo "Preparing to execute the sleep script"
              build:
                commands:
                  - echo "Starting the sleep script"
                  - |
                    #!/bin/bash
            
                    # Initialize total sleep time
                    total_sleep_time=60
                    sleep $total_sleep_time
                    # Loop until total sleep time reaches or exceeds 60 seconds
                    #while [ $total_sleep_time -lt 160 ]; do
                    #  echo $total_sleep_time
                    #  sleep $total_sleep_time
                    #  total_sleep_time=$((total_sleep_time + 15))
                      
                    #done
            
                    #echo "Total sleep time: $total_sleep_time seconds"
              post_build:
                commands:
                  - echo "Sleep script execution completed"









